version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: ./app/api/Dockerfile
    container_name: metis-api
    command: npm run dev
    volumes:
      - ./app/api:/var/www/current
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  swagger:
    image: swaggerapi/swagger-ui
    container_name: metis-swagger
    ports:
      - "4567:8080"
    environment:
      API_URL: "http://localhost:8080/documentation"
    depends_on:
      - api
