version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: ./app/api/Dockerfile
    container_name: metis-api
    command: npm run dev
    volumes:
      - ./app/api:/var/www/current
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MESSAGE_QUEUE: 'amqp://rabbitmq'
      GRAPHITE_URL: 'graphite:2003'
    depends_on:
      - rabbitmq

  grafana:
    build: './grafana'
    container_name: metis-grafana
    restart: always
    ports:
      - '3000:3000'

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: metis-graphite
    restart: always
    ports:
      - '2003:2003'
      - '2004:2004'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: metis-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: metis-swagger
    ports:
      - "4567:8080"
    environment:
      API_URL: "http://localhost:8080/documentation"
    depends_on:
      - api
